services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ticketing_system
      MYSQL_USER: adminuser
      MYSQL_PASSWORD: adminpass123
      MYSQL_ROOT_PASSWORD: adminpass123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    command: ["redis-server", "--port", "6380"]
    ports:
      - "6380:6380"

  web:
    build: ./backend
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: >
      sh -c "./wait-for-it.sh db:3306 -- celery -A server worker --pool=solo -l info"
    working_dir: /code
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./backend
    command: >
      sh -c "./wait-for-it.sh db:3306 -- celery -A server beat --loglevel=info"
    working_dir: /code
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis

  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    working_dir: /app
    command: sh -c "yarn install && yarn run dev --host"



volumes:
  mysql_data:
