# Generated by Django 4.2.5 on 2023-10-07 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 14, 49, 54, 504498)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='piecesjointes',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
