# Generated by Django 4.2.5 on 2023-10-08 01:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreponse',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tickets.ticketreponse'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 2, 28, 8, 70819)),
        ),
        migrations.AlterField(
            model_name='ticketreponse',
            name='piecesjointes',
            field=models.FileField(blank=True, null=True, upload_to='replies_attachments/'),
        ),
    ]
