# Generated by Django 4.2.5 on 2023-10-06 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('etat', models.CharField(choices=[('OUVERT', 'Ouvert'), ('ENCOURS', 'Encours'), ('RESOLU', 'Resolu'), ('EXPIRE', 'Expire')], default='OUVERT', max_length=10)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('piecesjointes', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('adz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assis_dz', to=settings.AUTH_USER_MODEL)),
                ('afr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assis_fr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('piecesjointes', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tickets.ticket')),
            ],
        ),
    ]
