# Generated by Django 4.2.5 on 2023-10-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(choices=[('OUVERT', 'Ouvert'), ('ENCOURS', 'Encours'), ('RESOLU', 'Resolu'), ('EXPIRE', 'Expire')], default='OUVERT', max_length=10),
        ),
    ]
