# Generated by Django 4.2.5 on 2023-10-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_deadline_alter_ticket_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('piecesjointes', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='tickets.ticket')),
            ],
        ),
    ]
