# Generated by Django 4.2.5 on 2023-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketreponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='piecesjointes',
            field=models.FileField(blank=True, null=True, upload_to='ticket_attachments/'),
        ),
    ]
