# Generated by Django 4.2.5 on 2023-10-07 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_deadline_alter_ticket_piecesjointes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 18, 38, 31, 465932)),
        ),
    ]
