# Generated by Django 4.2.5 on 2023-10-07 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 22, 40, 14, 381368)),
        ),
    ]
