# Generated by Django 4.2.5 on 2023-10-08 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_remove_ticketreponse_ticket_ticket_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 2, 28, 37, 980322)),
        ),
    ]
