# Generated by Django 4.2.5 on 2023-10-08 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 15, 42, 25, 29507)),
        ),
    ]
